repos:
  - repo: local
    hooks:
    - id: run-pytest
      name: Run pytest
      entry: ./run_tests.sh -v
      require_serial: true
      language: system
      types: [python]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
