repos:
  - repo: local
    hooks:
    - id: run-pytest
      name: Run pytest
      entry: ./run_tests.sh -v
      require_serial: true
      language: system
      types: [python]


  - repo: local
    hooks:
    - id: run-mypy
      name: Run mypy
      entry: ./run_mypy.sh -v
      require_serial: true
      language: system
      types: [python]