[tool.poetry]
name = "aoe2mapgenerator"
version = "0.1.4"
description = "Age of Empires II map generator"
authors = ["QuantumCreation <joseph6433@gmail.com>"]
readme = "README.md"
packages = [{include = "aoe2mapgenerator", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
AoE2ScenarioParser = "^0.1.56"
ipykernel = "^6.29.4"
numpy = "^1.26.4"
pyyaml = "^6.0.1"
matplotlib = "^3.9.0"
ujson = "^5.10.0"
types-ujson = "^5.10.0.20240515"
types-pyyaml = "^6.0.12.20240917"
mypy = "^1.15.0"
scipy = "^1.15.2"
pydeps = "^3.0.1"
pytest = "^8.3.5"
pydantic = "^2.0"


[tool.mypy]
files = ["src"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
